name: Docker CI

on:
  push:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build Docker
        run: docker build -t lila-gif .
      - name: Push Docker Image to ECR
        run: |
          export AWS_REGION='us-east-1'
          export AWS_ACCOUNT_ID='270576285979'
          export DOCKER_FILE='lila-gif'
          export DOCKER_FILE_VERSION='latest'
          export DOCKER_TAG='latest'
          export COMMIT_TAG=$(git rev-parse --short HEAD)
          (aws ecr create-repository --repository-name $DOCKER_FILE) || true
          docker tag $DOCKER_FILE:$DOCKER_FILE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_FILE:$DOCKER_TAG
          docker tag $DOCKER_FILE:$DOCKER_FILE_VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_FILE:$COMMIT_TAG
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          docker push --all-tags $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_FILE
      - name: Force lila stack staging redeploy
        run: aws ecs update-service --cluster lila-stack-staging --service lila-stack-service-staging --force-new-deployment | jq .
